In [2]:
import numpy as np

In [4]:
# 1. Sukurkite toki ndarray ir issaugokite kintamajame arr:

arr = np.array ([
    [5,4,3],
    [3,2,1],
    [1,0,6],
    [6,5,4]
]
)

print(arr)

[[5 4 3]
 [3 2 1]
 [1 0 6]
 [6 5 4]]


In [6]:
# 2. Kiek dimensiju turi arr? Kokios jos?

print(arr.shape)

# Arr turi dvi dimensijas, 4 * 3 (keturios eilutes ir 3 stulpeliai)

(4, 3)


In [14]:
# 3. Atspausdinkite 3-ios eilutes antraji nari

print(arr[2,1])

0


In [13]:
# 4. Atspausdinkite 2-os eilutes pirma ir antra narius

print(arr[1, 0:2])

[3 2]


In [12]:
# 5. Atspausdinkite 3-ios ir 4 eiluciu antra ir trecia narius (t.y. is viso 4 skaicius is desiniojo apatinio kampo)

print(arr[2:, 1:])

[[0 6]
 [5 4]]


In [23]:
# 6. Naudodami reshape() metoda pakeiskite arr taip, kad jo dimensija butu (6,2)

print(arr)
print(arr.shape)


new_dimension = arr.reshape(6,2)
print(new_dimension)
print(new_dimension.shape)

[[5 4 3]
 [3 2 1]
 [1 0 6]
 [6 5 4]]
(4, 3)
[[5 4]
 [3 3]
 [2 1]
 [1 0]
 [6 6]
 [5 4]]
(6, 2)


In [30]:
# 7. Transponuokite arr (po transponavimo shape turi buti 2,6)

print(new_dimension)
print(new_dimension.shape)

print('\n')

Tr = new_dimension.T
print(Tr)
print(Tr.shape)

[[5 4]
 [3 3]
 [2 1]
 [1 0]
 [6 6]
 [5 4]]
(6, 2)


[[5 3 2 1 6 5]
 [4 3 1 0 6 4]]
(2, 6)


In [38]:
# 8. Padauginkite visus sio array skaicius is 8 ir atimkite is visu 30, issaugokite kintamajame arr_2

print(Tr)
print('\n')
arr_2 = ((Tr * 8) - 30)
print(arr_2)

[[5 3 2 1 6 5]
 [4 3 1 0 6 4]]


[[ 10  -6 -14 -22  18  10]
 [  2  -6 -22 -30  18   2]]


In [57]:
# 9. Priskirkite visus neigiamus arr_2 narius kintamajam arr_2_neg
#print(arr_2)

arr_2_neg = arr_2[arr_2 < 0]
print(arr_2_neg)



[ -6 -14 -22  -6 -22 -30]


In [65]:
# 10. Atspausdinkite arr_2_neg nariu suma ir sandauga

mult = 1
for number in arr_2_neg:
    mult *= number
print(mult)

7318080


In [96]:
# 11. Atspausdinkite arr_2_neg mediana

print(arr_2_neg)
print('\n')
arr_2_neg.sort()
print(arr_2_neg)
print('\n')
arr_index_2 = arr_2_neg[2]
arr_index_3 = arr_2_neg[3]
median = ((arr_index_2 + arr_index_3) / 2)
print(median)

[-30 -22 -22 -14  -6  -6]


[-30 -22 -22 -14  -6  -6]


-18.0
