# Namu darbai

In [1]:
# Rasti pasikartojancius elementus tarp dvieju list

a = [1,2,3,4,5,6,7,8,9,15]
b = [3,8,9,11,15]

print(list(set(a).intersection(b)))

[8, 9, 3, 15]


In [2]:
for number in range(1,101):
    if number % 6 == 0:
        print(number,'FizzBuzz')
    elif number % 3 == 0:
        print(number,'Buzz')
    elif number % 2 == 0:
        print(number, 'Fizz')


2 Fizz
3 Buzz
4 Fizz
6 FizzBuzz
8 Fizz
9 Buzz
10 Fizz
12 FizzBuzz
14 Fizz
15 Buzz
16 Fizz
18 FizzBuzz
20 Fizz
21 Buzz
22 Fizz
24 FizzBuzz
26 Fizz
27 Buzz
28 Fizz
30 FizzBuzz
32 Fizz
33 Buzz
34 Fizz
36 FizzBuzz
38 Fizz
39 Buzz
40 Fizz
42 FizzBuzz
44 Fizz
45 Buzz
46 Fizz
48 FizzBuzz
50 Fizz
51 Buzz
52 Fizz
54 FizzBuzz
56 Fizz
57 Buzz
58 Fizz
60 FizzBuzz
62 Fizz
63 Buzz
64 Fizz
66 FizzBuzz
68 Fizz
69 Buzz
70 Fizz
72 FizzBuzz
74 Fizz
75 Buzz
76 Fizz
78 FizzBuzz
80 Fizz
81 Buzz
82 Fizz
84 FizzBuzz
86 Fizz
87 Buzz
88 Fizz
90 FizzBuzz
92 Fizz
93 Buzz
94 Fizz
96 FizzBuzz
98 Fizz
99 Buzz
100 Fizz


In [9]:
for numbers in range(1,101):
    result_text = ''
    if numbers % 2 == 0:
        result_text += 'Fizz'
    if numbers % 3 == 0:
        result_text +='Buzz'
    print(numbers, result_text)
    


1 
2 Fizz
3 Buzz
4 Fizz
5 
6 FizzBuzz
7 
8 Fizz
9 Buzz
10 Fizz
11 
12 FizzBuzz
13 
14 Fizz
15 Buzz
16 Fizz
17 
18 FizzBuzz
19 
20 Fizz
21 Buzz
22 Fizz
23 
24 FizzBuzz
25 
26 Fizz
27 Buzz
28 Fizz
29 
30 FizzBuzz
31 
32 Fizz
33 Buzz
34 Fizz
35 
36 FizzBuzz
37 
38 Fizz
39 Buzz
40 Fizz
41 
42 FizzBuzz
43 
44 Fizz
45 Buzz
46 Fizz
47 
48 FizzBuzz
49 
50 Fizz
51 Buzz
52 Fizz
53 
54 FizzBuzz
55 
56 Fizz
57 Buzz
58 Fizz
59 
60 FizzBuzz
61 
62 Fizz
63 Buzz
64 Fizz
65 
66 FizzBuzz
67 
68 Fizz
69 Buzz
70 Fizz
71 
72 FizzBuzz
73 
74 Fizz
75 Buzz
76 Fizz
77 
78 FizzBuzz
79 
80 Fizz
81 Buzz
82 Fizz
83 
84 FizzBuzz
85 
86 Fizz
87 Buzz
88 Fizz
89 
90 FizzBuzz
91 
92 Fizz
93 Buzz
94 Fizz
95 
96 FizzBuzz
97 
98 Fizz
99 Buzz
100 Fizz


# Numpy

In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\laima\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [11]:
import numpy as np

In [19]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
print(a_list)
print(a_list[1][1])
print( [row[1]for row in a_list] )


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
6
[2, 6, 10]


In [29]:
a_np = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
)
print(a_np)
print(type(a_np))
print(a_np[1][1])
print('\n')
print(a_np[1,1]) # row index, column index
print('\n')
print(a_np[:, 1])
print('\n')
print(a_np[:2, 1])
print('\n')
print(a_np[:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
6


6


[ 2  6 10]


[2 6]


[[2 3]
 [6 7]]


In [36]:
print(a_np.shape)
print(len(a_np)) # pirmos asies dydis

(3, 4)
3


# 1D array

In [33]:
array_1d = np.array([1,5,7,9,71,14])
print(array_1d.shape)
print(len(array_1d)) # 

(6,)
6


In [37]:
print(array_1d)

[ 1  5  7  9 71 14]


# 3D array

In [38]:
arr_3d = np.array([
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [1, 2, 3,],
            [4, 5, 6]
        ]
    ]
)

In [39]:
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [40]:
print(arr_3d.shape)

(2, 2, 3)


In [51]:
n_dim_array = np.random.randn(2,5,3,4,4,4,4)
print(n_dim_array.shape)
print(n_dim_array)


(2, 5, 3, 4, 4, 4, 4)
[[[[[[[-4.70223982e-01 -7.29163049e-01  4.02069502e-01
       -2.10903013e+00]
      [ 2.59614212e-01  1.63511317e+00  7.98894529e-01
        1.34472231e+00]
      [ 3.81763383e-01 -1.10517085e+00 -5.01268265e-02
       -1.59683476e+00]
      [ 1.07514056e+00 -3.55302152e-01 -1.35873642e-01
       -3.14653146e-01]]

     [[-1.28554830e+00  1.65675874e+00 -3.53605654e-01
        1.97316671e+00]
      [ 1.84923948e+00  2.41983071e-01 -1.12888074e+00
       -1.83154420e-01]
      [-6.25032725e-01  1.49667185e+00 -1.04518361e+00
       -1.20348318e+00]
      [-9.07507211e-01  4.64315227e-01  1.75073965e-01
       -3.75973052e-01]]

     [[ 1.34095392e+00  1.16579932e+00 -1.13262521e-02
       -9.05526303e-01]
      [-7.21177696e-02  1.59664336e+00 -6.23261200e-01
        8.74986544e-01]
      [-3.91141094e-02  9.36837849e-01  4.54775498e-01
       -2.16593209e+00]
      [ 9.96615351e-01  2.92799145e-01  6.22613868e-01
       -4.14904131e-01]]

     [[-2.22465598e-01  

# Numby operations

In [53]:
py_list = [1,2,3,4,5]
print(py_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [54]:
np_array = np.array([1,2,3,4,5])

In [55]:
print(np_array * 3)

[ 3  6  9 12 15]


In [56]:
print(np_array / 3)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [57]:
print(np_array ** 3)

[  1   8  27  64 125]


In [59]:
print(py_list)
py_list[2:4] = 100

[1, 2, 3, 4, 5]


TypeError: can only assign an iterable

In [61]:
np_array[2:4] = 100 # pakeicia reiksmes i 100
print(np_array)
np_array[2:4] = [100, 200]
print(np_array)
# np_array[2:4] = [100,200,300] #wrong shapes

[  1   2 100 100   5]
[  1   2 100 200   5]


# Numpy speed

In [63]:
size = 100000

In [64]:
py_list = list(range(size))

In [65]:
np_arr = np.arange(size)

In [69]:
%%timeit # Jupyter command

list_rez = []
for number in py_list:
    list_rez.append(number * 10)


14.6 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [70]:
%%timeit # Jupyter command

np_rez = np_arr * 10

138 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Reshape

In [73]:
np_array = np.arange(0, 100, 2)
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [75]:
print(np_array.reshape( (5, 10) )) # is vektoriaus pasidaro matrica

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [81]:
print(np_array.reshape((1, 10, 5)))

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [82]:
print(np_array.reshape((2, 1, -1)))

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


In [92]:
array_2d = np.array( [ [1,2], [4,3], [7,4] ] )
print(array_2d)
print(array_2d.shape)

array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [1,2], [4,3], [7,4] ],
    [ [1,2], [4,3], [7,4] ],
    [ [1,2], [4,3], [7,4] ],
]
)
     
print('3D\n', array_3d)
print(array_3d.shape)

[[1 2]
 [4 3]
 [7 4]]
(3, 2)
3D
 [[[1 2]
  [4 3]
  [7 4]]

 [[1 2]
  [4 3]
  [7 4]]

 [[1 2]
  [4 3]
  [7 4]]

 [[1 2]
  [4 3]
  [7 4]]]
(4, 3, 2)


# numpy methods

In [94]:
np.mean(array_3d)

3.5

In [95]:
np.mean(array_3d, axis=0)

array([[1., 2.],
       [4., 3.],
       [7., 4.]])

In [98]:
print(array_2d)
print('Column mean', np.mean(array_2d, axis=0))
print('Row mean', np.mean(array_2d, axis=1))

[[1 2]
 [4 3]
 [7 4]]
Column mean [4. 3.]
Row mean [1.5 3.5 5.5]


In [103]:
np.std(array_2d)
print('Column std', np.std(array_2d, axis=0))

Column std [2.44948974 0.81649658]


In [104]:
np.sum(array_2d)
print('Column sum', np.sum(array_2d, axis=0))
print('Row sum', np.sum(array_2d, axis=1))

Column sum [12  9]
Row sum [ 3  7 11]


In [105]:
array_2d.transpose()

array([[1, 4, 7],
       [2, 3, 4]])

In [106]:
array_2d.T

array([[1, 4, 7],
       [2, 3, 4]])

# Comparisons

In [109]:
np_array = np.arange(0,60,2)
print(np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58]


In [113]:
np_array [ np_array < 30]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [116]:
np_array < 30

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [118]:
np_array [ np_array % 3 == 0]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])