# Numpy biblioteka

In [1]:
# Skirta skaiciavimams

In [5]:
# numpy modulio pagrindinis objektas - ndarray (n-matis masyvas) array = masyvas
# galime tureti visokiu formu modulius,
# pvz 1D array - vienos dimensijos duomenys, panasus si sarasus (1D array - vektoriai)
# skirtumas nuo sarasu - negalime labai lengvai prideti nauju duomenu
# 2D array - 2d masyvas, matrica su eilutem ir stulpeliais
# 3D array - triju dimensiju matrica

In [ ]:
# visos matricos (ar vektoriai) turi shape.
# 3D matricos forma (4,3,2)

In [17]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

# dvieju dimensiju sarasas

print(a_list)
print(a_list[1][1])
print([row[1] for row in a_list]) # skirtingu eiliu tie patys indeksai su for cycle isgaunami

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
6
[2, 6, 10]


In [10]:
import numpy as np

# 2D array

In [19]:
a_np = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
) 
# np.array - sarasa konvertuoja i masyva
print(a_np) # atspausdina nebe kaip lista, o kaip matrica, nes np.array pakeicia i masyva
print(type(a_np)) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [24]:
# kaip isaugoti ta pati 6 is array

print(a_np[1][1])
print('\n')
print(a_np[1,1]) # pirmos eiles pirmo stulpelio ROW INDEX COLUMN INDEX ; pirmos eiles pirmas stulpelis
print('\n')
print(a_np[:, 1]) # isgauti visu eiliu pirma index
print('\n')
print(a_np[:2, 1]) # 0 ir 1 eiles pirmas index
print('\n')
print(a_np[:2, 1:3]) # 0 ir 1 eiles 1 ir antras index /paimti nuo pradzios iki antros eiles pirma ir antra stulpa

6


6


[ 2  6 10]


[2 6]


[[2 3]
 [6 7]]


In [33]:
print(a_np.shape)
print(len(a_np)) # pirmos asies dydis

(3, 4)
3


# 1D array

In [ ]:
# 1 dimencijos matrica (vektorius)

In [26]:
array_1d = np.array(
    [1,5,7,9,71,14]
)

In [34]:
print(array_1d.shape)
print(len(array_1d))

(6,)
6


In [35]:
print(array_1d)

[ 1  5  7  9 71 14]


# 3D array


In [36]:
arr_3d = np.array([
        [
            [1, 2, 3],
            [4, 5, 6],
        ],
        [
            [1, 2, 3,],
            [4, 5, 6]
        ]
    ]
)

# du nariai, po dvi eiles po 3 s

In [37]:
print(arr_3d) # 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [38]:
print(arr_3d.shape)

(2, 2, 3)


In [44]:
n_dim_array = np.random.randn(2,5,3)
print(n_dim_array.shape)
print(n_dim_array)

# sugeneruoja matricas randomly nurodzius forma

(2, 5, 3)
[[[ 1.26072125  0.015521    0.85115622]
  [ 0.14248699 -0.82091512  0.98816652]
  [-0.31445905 -0.47693095 -0.90124973]
  [-1.51138859  0.90962953  0.84746733]
  [ 1.55937884 -2.13194556 -0.05310899]]

 [[ 0.43300148 -1.32374524  0.3832497 ]
  [-1.20386052 -0.15326386  0.92000353]
  [ 1.1367815  -0.21101391 -0.78413387]
  [-0.16914331  0.61834202  1.28208518]
  [ 0.5457918   0.86890803  2.85589554]]]


# Numpy operations

In [46]:
py_list = [1,2,3,4,5] # su listu
print(py_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [50]:
# su numpy

np_array = np.array ( [1,2,3,4,5] )

print(np_array * 3) # sudaugina kiekviena verte, su list pakartoja 3 k

[ 3  6  9 12 15]


In [51]:
print(np_array / 3)
print(np_array ** 3)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[  1   8  27  64 125]


In [54]:
print(py_list)
py_list[2:4] = 100 # list neleidzia pakeisti keliu nariu vienu metu

[1, 2, 3, 4, 5]


TypeError: can only assign an iterable

In [57]:
np_array[2:4] = 100
print(np_array)
np_array[2:4] = [100,200]
print(np_array)
# np_array[2:4] = [100,200,300] #wrong shapes

[  1   2 100 100   5]
[  1   2 100 200   5]


## Reshape

In [62]:
# galime susikurti 

np_array = np.arange(0,100,2) # sarasas, kurio forma yra vektorius 50 skaiciu
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [63]:
# galime manipuliuoti forma ir padaryti 2D is 1D

print(np_array.reshape( (5,10) )) # is vektoriaus matrica

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [65]:
print(np_array.reshape( (2,5,5) )) # 3D matrica / 5*5  2d matrivos

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [68]:
print(np_array.reshape((1, 10, 5)))

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [67]:
print(np_array.reshape((2,1,-1)))

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


In [73]:
array_2d = np.array( [ [1,2], [4,3], [7,4] ] )
print('2D', array_2d)
print(array_2d.shape)

array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)
     
print('3D\n', array_3d)
print(array_3d.shape)

2D [[1 2]
 [4 3]
 [7 4]]
(3, 2)
3D
 [[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]
(4, 3, 2)


# Numpy methods

In [75]:
np.mean(array_3d) # visos matricos visu skaiciu vidurkis

3.75

In [80]:
print(array_2d)
print('column mean:', np.mean(array_2d, axis=0)) # stulpeliu vidurkis)
print('row mean:', np.mean(array_2d, axis=1))

[[1 2]
 [4 3]
 [7 4]]
column mean: [4. 3.]
row mean: [1.5 3.5 5.5]


In [84]:
# standartinis nuokrypis
print(array_2d)
np.std(array_2d)


print('Column std', np.std(array_2d, axis=0))

[[1 2]
 [4 3]
 [7 4]]
Column std [2.44948974 0.81649658]


In [87]:
print('column sum', np.sum(array_2d,axis=0))
print('row sum', np.sum(array_2d,axis=1))

column sum [12  9]
row sum [ 3  7 11]


In [89]:
array_2d.transpose() # 3*2 = 2*3

array([[1, 4, 7],
       [2, 3, 4]])

# Comparisons

In [90]:
np_array = np.arange(0,60,2) # arange - sukuria matrica pagal duotus duomenis
print(np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58]


In [91]:
# suzinoti, kurie skaiciai didesni uz 30

np_array[np_array < 30]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [94]:
np_array < 30 # masking

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [93]:
np_array[np_array % 3 ==0]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])